name: umpsa_care
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.2.3

  #  Firebase dependencies
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.4.0
  http: ^1.2.0
  image_picker: ^1.2.0
  flutter_typeahead: ^5.1.0
  dropdown_search: ^5.0.6
  firebase_messaging: ^14.0.0
  flutter_local_notifications: ^17.0.0
  awesome_notifications: ^0.10.0
  carousel_slider: ^5.1.0
  timezone: ^0.9.2
  onesignal_flutter: ^5.0.0

  #  Utilities
  intl: ^0.20.0
  uuid: ^4.2.1
  table_calendar: ^3.0.9

  #  State management
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/

